Thc.Web/Controllers/AlquilerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using Thc.Interfaces.Services;
using Thc.Models.Models;
using Thc.Services.Services;


namespace Thc.Web.Controllers
{
    public class AlquilerController : Controller
    {
        //
        // GET: /Alquiler/

        private readonly IAlquilerService service;
        public AlquilerController(IAlquilerService service)
        {
            this.service = service;
        }

        [HttpGet]
        public ViewResult Index()
        {
            return View("Index", service.All());
        }

        [HttpGet]
        public ActionResult Create()
        {
            var clientes = service.GetClientes();
            var autos = service.GetAutos();
            var conductores = service.GetConductores();

            ViewData["ClienteId"] = new SelectList(clientes, "Id", "NombresRazonSocial");
            ViewData["AutoId"] = new SelectList(autos, "Id", "Placa");
            ViewData["ConductorId"] = new SelectList(conductores, "Id", "NameConductor");

            return View("Create");
        }

        [HttpGet]
        public ActionResult Details(int id)
        {
            if (id == 0)
                return RedirectToAction("Index");
            return View("Details", service.GetById(id));
        }

        [HttpPost]
        public ActionResult Create(Alquiler alquiler)
        {
            service.Insert(alquiler);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            var model = service.GetById(id);
            return View("edit", model);
        }

        [HttpPost]
        public ActionResult Edit(Alquiler post)
        {
            if (ModelState.IsValid)
            {
                service.Update(post);
                return RedirectToAction("Index");
            }
            return View("Edit", post);
        }


    }
}

Thc.Web/Views/Alquiler/Create.cshtml
@model Thc.Models.Models.Alquiler

@{
    ViewBag.Title = "Registrar Alquiler";
}

<script type="text/javascript">

        function myFunction() {

            var d1 = $("#from").val().split("/");
            var dat1 = new Date(d1[2], parseFloat(d1[1]) - 1, parseFloat(d1[0]));
            var d2 = $("#to").val().split("/");
            var dat2 = new Date(d2[2], parseFloat(d2[1]) - 1, parseFloat(d2[0]));

            var fin = dat2.getTime() - dat1.getTime();
            var dias = Math.floor(fin / (1000 * 60 * 60 * 24)) + 1

            var total = dias * $("#MontoXdia").val()

            $("#NroDias").val(dias);
            $("#MontoTotal").val(total);
        }

</script>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)
       
   	<div class="row clearfix">
		<div class="col-md-1 column">
		</div>
		<div class="col-md-11 column">


        <div class="panel panel-primary" style="width:100%">
                      <div class="panel-heading">
                        <b>Datos del Servicio de Alquiler</b>
                      </div>
                        <div class="panel-body">

	                    <div class="row clearfix">
		                    <div class="col-md-3 column">

                                <div class="editor-label">
                                    @Html.Label("Cliente")
                                </div>
                                <div class="editor-field">
                                    <div class="input-group" style="width:89%">
                                      <div class="input-group-addon" style="width:0.009%"><img src="~/Content/icons/cliente-icon.png" width="18px"/></div>
                                        @Html.DropDownListFor(model => model.ClienteId, (SelectList)ViewBag.ClienteId, new {@class="selectpicker"})
                                    </div>
                                    <p>
                                    @Html.ValidationMessageFor(model => model.ClienteId)
                                    </p>
                                </div>

@*                                <div class="editor-label">
                                    @Html.Label("Usuario")
                                </div>
                                <div class="editor-field">
                                    <div class="input-group" style="width:89%">
                                      <div class="input-group-addon" style="width:0.009%"><img src="~/Content/icons/user-icon.png" width="18px"/></div>
                                        @Html.DropDownListFor(model => model.UsuarioId, (SelectList)ViewBag.UsuarioId, new {@class="selectpicker"})
                                    </div>
                                    <p>
                                    @Html.ValidationMessageFor(model => model.UsuarioId)
                                    </p>
                                </div>*@

                                <div class="editor-label">
                                    @Html.Label("Fecha de Registro")
                                </div>
                                <div class="editor-field">
                                   <div class="input-group">
                                      <div class="input-group-addon"><img src="~/Content/icons/fecha-icon.png" width="18px"/></div>
                                       @Html.TextBoxFor(model => model.FechaServicio, new {id="datepicker", style="width:100px", @readonly="readonly"})
                                    </div>
                                   <p>
                                    @Html.ValidationMessageFor(model => model.FechaServicio)
                                    </p>
                                </div>

                                <div class="editor-label">
                                    @Html.Label("Hora de Registro")
                                </div>
                                <div class="editor-field">

                                    <div class="bfh-timepicker" data-name="HoraServicio" data-mode="12h" style="width:75%; z-index: 1;">
                                    </div>

                                   <p>
                                    @Html.ValidationMessageFor(model => model.HoraServicio)
                                    </p>
                                </div>

                                <div class="editor-label">
                                    @Html.Label("Lugar Referencia")
                                </div>
                                <div class="editor-field">
                                    <div class="input-group">
                                      <div class="input-group-addon"><img src="~/Content/icons/city2-icon.png" width="18px"/></div>
                                       @Html.TextBoxFor(model => model.LugarReferencia, new { style="width:180px"})
                                    </div>
                                   <p>
                                    @Html.ValidationMessageFor(model => model.LugarReferencia)
                                    </p>
                                </div>

                            </div>
		                    <div class="col-md-1 column">
		                    </div>
                            <div class="col-md-3 column">

                                <div class="editor-label">
                                    @Html.Label("Conductor")
                                </div>
                                <div class="editor-field">
                                    <div class="input-group" style="width:89%">
                                      <div class="input-group-addon" style="width:0.009%"><img src="~/Content/icons/driver-icon.png" width="18px"/></div>
                                        @Html.DropDownListFor(model => model.ConductorId, (SelectList)ViewBag.ConductorId, new {@class="selectpicker"})
                                    </div>
                                    <p>
                                    @Html.ValidationMessageFor(model => model.ConductorId)
                                    </p>
                                </div>

                                <div class="editor-label">
                                    @Html.Label("Vehículo")
                                </div>
                                <div class="editor-field">
                                    <div class="input-group" style="width:89%">
                                      <div class="input-group-addon" style="width:0.009%"><img src="~/Content/icons/auto-icon.png" width="18px"/></div>
                                        @Html.DropDownListFor(model => model.AutoId, (SelectList)ViewBag.AutoId, new {@class="selectpicker"})
                                    </div>
                                    <p>
                                    @Html.ValidationMessageFor(model => model.AutoId)
                                    </p>
                                </div>

                                <div class="editor-label">
                                    @Html.Label("Monto por Día")
                                </div>
                                <div class="editor-field">
                                    <div class="input-group">
                                      <div class="input-group-addon"><img src="~/Content/icons/cash1-icon.png" width="18px"/></div>
                                       @Html.TextBoxFor(model => model.MontoXdia, new { style="width:100px"})
                                    </div>
                                   <p>
                                    @Html.ValidationMessageFor(model => model.MontoXdia)
                                    </p>
                                </div>

                            </div>
		                    <div class="col-md-1 column">
		                    </div>
                            <div class="col-md-3 column">


                                <div class="editor-label">
                                    @Html.Label("Fecha de Inicio")
                                </div>
                                <div class="editor-field">
                                    <div class="input-group">
                                      <div class="input-group-addon"><img src="~/Content/icons/calendar1-icon.png" width="18px"/></div>
                                       @Html.TextBoxFor(model => model.FechaInicio, new {id="from", style="width:100px", @readonly="readonly"})
                                    </div>
                                   <p>
                                    @Html.ValidationMessageFor(model => model.FechaInicio)
                                    </p>
                                </div>

                                <div class="editor-label">
                                    @Html.Label("Fecha Fin")
                                </div>
                                <div class="editor-field">
                                    <div class="input-group">
                                      <div class="input-group-addon"><img src="~/Content/icons/calendar1-icon.png" width="18px"/></div>
                                       @Html.TextBoxFor(model => model.FechaFin, new {onChange="myFunction()", id="to", style="width:100px", @readonly="readonly"})
                                    </div>
                                   <p>
                                    @Html.ValidationMessageFor(model => model.FechaFin)
                                    </p>
                                </div>

                                <div class="editor-label">
                                    @Html.Label("N° de Días")
                                </div>
                                <div class="editor-field">
                                    <div class="input-group">
                                      <div class="input-group-addon"><img src="~/Content/icons/days-icon.png" width="18px"/></div>
                                       @Html.TextBoxFor(model => model.NroDias, new {style="width:50px", @readonly="readonly"})
                                    </div>
                                   <p>
                                    @Html.ValidationMessageFor(model => model.NroDias)
                                    </p>
                                </div>



                                <div class="editor-label">
                                    @Html.Label("Monto Total")
                                </div>
                                <div class="editor-field">
                                    <div class="input-group">
                                      <div class="input-group-addon"><img src="~/Content/icons/cash2-icon.png" width="18px"/></div>
                                       @Html.TextBoxFor(model => model.MontoTotal, new { style="width:120px", @readonly="readonly"})
                                    </div>
                                   <p>
                                    @Html.ValidationMessageFor(model => model.MontoTotal)
                                    </p>
                                </div>

                            </div>                            

                        </div>

                        </div>
                    </div>            


		</div>
	</div>
        
    <div class="row clearfix">
	    <div class="col-md-11 column" style="text-align:center">
            <p>
                <button type="submit" class="btn btn-success">GRABAR</button>&nbsp;&nbsp;
                <a href="@Url.Action("Index", "Alquiler")" class="btn btn-danger" style="margin: auto; color: #ffffff;">
                    CANCELAR
                </a>
            </p>
        </div>
    </div>

}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Thc.Web/Views/Alquiler/Index.cshtml
@model IEnumerable<Thc.Models.Models.Alquiler>

@{
    ViewBag.Title = "Lista de Alquileres";
}

<div class="panel panel-primary">
  <div class="panel-heading">
    <h1>Lista de Alquileres</h1>
  </div>
  <div class="panel-body">
    <form method="GET" class="navbar-form navbar-left" role="search">
        <div class="form-group">
            <input type="text" name="buscar" class="form-control" size="60"/>
        </div>&nbsp;&nbsp;&nbsp;
        <button type="submit" class="btn btn-info">Buscar</button>
    </form>
    <div align="right">
        <a href="@Url.Action("Create", "Alquiler")" class="btn btn-warning" style="margin: auto; color: #ffffff;">
            Registrar Alquiler
        </a>
    </div>
  </div>

  <div class="panel-body">
    <table class="table table-condensed table-striped">
      <tr class="info text-primary" style="font-size:12.5px; text-align:center">
        <th>
            Cliente
        </th>
        <th>
            Lugar Referencia
        </th>
        <th>
            Conductor
        </th>
        <th>
            Vehículo
        </th>
        <th>
            Fechas
        </th>
        <th>
            Nro. Dias
        </th>
        <th>
            Monto x Día
        </th>
        <th>
            Monto Total
        </th>
        <th>
            Acción
        </th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Cliente.NombresRazonSocial) @Html.DisplayFor(modelItem => item.Cliente.AppPaterno) @Html.DisplayFor(modelItem => item.Cliente.AppMaterno)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LugarReferencia)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Conductor.NameConductor)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Auto.Unidad.DescripcionUnidad) / @Html.DisplayFor(modelItem => item.Auto.Placa)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FechaInicio) @Html.DisplayFor(modelItem => item.FechaFin)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NroDias)
        </td>
        <td>
            S/. @Html.DisplayFor(modelItem => item.MontoXdia)
        </td>
        <th>
            S/. @Html.DisplayFor(modelItem => item.MontoTotal)
        </th>
            <td align="right">
                <img src="~/Content/icons/pencil-icon.png" title="Editar" width="16px"/>&nbsp;
                <a href="@Url.Action("Delete", new { Id = item.Id})">
                    <img src="~/Content/icons/delete-icon.png" title="Eliminar" width="18px"/>
                </a>
            </td>
        </tr>
    }
    </table>
  </div>
</div>