Thc.Web/Controllers/AutoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using Thc.Interfaces.Services;
using Thc.Models.Models;
using Thc.Services.Services;
using Thc.DB.DB;

//Para el Path de Imagenes
using System.IO;

namespace Thc.Web.Controllers
{
    public class AutoController : Controller
    {
        //
        // GET: /Auto/

        private readonly IAutoService service;

        public AutoController(IAutoService service)
        {
            this.service = service;
        }

        [HttpGet]
        public ViewResult Index()
        {
            return View("Index", service.All());
        }

        [HttpGet]
        public ActionResult Create()
        {
            var estados = service.GetEstados();
            var unidades = service.GetUnidades();

            ViewData["EstadoId"] = new SelectList(estados, "Id", "DescripcionEstado");
            ViewData["UnidadId"] = new SelectList(unidades, "Id", "DescripcionUnidad");

            return View("Create");
        }

        [HttpGet]
        public ActionResult Details(int id)
        {
            if (id == 0)
                return RedirectToAction("Index");
            return View("Details", service.GetById(id));
        }

        [HttpPost]
        public ActionResult Create(Auto auto)
        {
            service.Insert(auto);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            var model = service.GetById(id);
            return View("edit", model);
        }

        [HttpPost]
        public ActionResult Edit(Auto post)
        {
            if (ModelState.IsValid)
            {
                service.Update(post);
                return RedirectToAction("Index");
            }
            return View("Edit", post);
        }

        [HttpPost]
        public ActionResult UploadImage(string imageName, string contentType, string imageData)
        {
            byte[] data = Convert.FromBase64String(imageData);

            if (Request.IsAjaxRequest())
                return Content(imageData);

            return File(data, contentType, imageName);
        }

        //public FileContentResult GetImage(Int32 CategoryID)
        //{
        //    Auto cat = entities.Autos.FirstOrDefault(c => c.Id == CategoryID);

        //    if (cat != null)
        //    {

        //        string type = string.Empty;
        //        if (!string.IsNullOrEmpty(cat.ImageMimeType))
        //        {
        //            type = cat.ImageMimeType;
        //        }
        //        else
        //        {
        //            type = "image/jpeg";
        //        }

        //        return File(cat.Picture, type);
        //    }
        //    else
        //    {
        //        return null;
        //    }
        //}


        //[HttpPost]
        //public ActionResult SendImage(HttpPostedFileBase img)
        //{
        //    var data = new byte[img.ContentLength];
        //    img.InputStream.Read(data, 0, img.ContentLength);
        //    var path = ControllerContext.HttpContext.Server.MapPath("/");
        //    var filename = Path.Combine(path, Path.GetFileName(img.FileName));
        //    System.IO.File.WriteAllBytes(Path.Combine(path, filename), data);
        //    ViewBag.ImageUploaded = filename;
        //    return View("Index");
        //}

        //public ActionResult Preview(string file)
        //{
        //    var path = ControllerContext.HttpContext.Server.MapPath("/");
        //    if (System.IO.File.Exists(Path.Combine(path, file)))
        //    {
        //        return File(Path.Combine(path, file), "image/jpeg");
        //    }
        //    return new HttpNotFoundResult();
        //}
    }
}

Thc.Web/Controllers/ProveedorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using Thc.Interfaces.Services;
using Thc.Models.Models;
using Thc.Services.Services;


namespace Thc.Web.Controllers
{
    public class ProveedorController : Controller
    {
        //
        // GET: /Proveedor/

        private readonly IProveedorService service;

        public ProveedorController(IProveedorService service)
        {
            this.service = service;
        }

        [HttpGet]
        public ViewResult Index()
        {
            return View("Index", service.All());
        }

        [HttpGet]
        public ActionResult Create()
        {
            var ciudades = service.GetCiudades();

            ViewData["CiudadId"] = new SelectList(ciudades, "Id", "NameCiudad");

            return View("Create");
        }

        [HttpGet]
        public ActionResult Details(int id)
        {
            if (id == 0)
                return RedirectToAction("Index");
            return View("Details", service.GetById(id));
        }


        [HttpPost]
        public ActionResult Create(Proveedor proveedor)
        {
            if (ModelState.IsValid)
            {
                service.Insert(proveedor);
                return RedirectToAction("Index");
            }
            return View("Create", proveedor);
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            var model = service.GetById(id);
            return View("edit", model);
        }

        [HttpPost]
        public ActionResult Edit(Proveedor post)
        {
            if (ModelState.IsValid)
            {
                service.Update(post);
                return RedirectToAction("Index");
            }
            return View("Edit", post);
        }

    }
}

Thc.Web/Views/Auto/Create.cshtml
@model Thc.Models.Models.Auto

@{
    ViewBag.Title = "Crear Vehículo";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    
	<div class="row clearfix">

		<div class="col-md-1 column">
		</div>
		<div class="col-md-11 column">


        <div class="panel panel-primary" style="width:85%">
                      <div class="panel-heading">
                        <b>Datos del Proveedor</b>
                      </div>
                        <div class="panel-body">

	                    <div class="row clearfix">
		                    <div class="col-md-5 column">

                                <div class="editor-label">
                                    @Html.Label("Placa")
                                </div>
                                <div class="editor-field">
                                    <div class="input-group">
                                      <div class="input-group-addon"><img src="~/Content/icons/placa-icon.png" width="18px"/></div>
                                       @Html.TextBoxFor(model => model.Placa, new { style="width:204px"})
                                    </div>
                                   <p>
                                    @Html.ValidationMessageFor(model => model.Placa)
                                    </p>
                                </div>

                                <div class="editor-label">
                                    @Html.Label("Unidad")
                                </div>
                                <div class="editor-field">
                                    <div class="input-group" style="width:89%">
                                      <div class="input-group-addon" style="width:0.009%"><img src="~/Content/icons/auto-icon.png" width="18px"/></div>
                                        @Html.DropDownListFor(model => model.UnidadId, (SelectList)ViewBag.UnidadId, new {@class="selectpicker"})
                                    </div>
                                    <p>
                                    @Html.ValidationMessageFor(model => model.UnidadId)
                                    </p>
                                </div>

                                <div class="editor-label">
                                    @Html.Label("Estado")
                                </div>
                                <div class="editor-field">
                                    <div class="input-group" style="width:89%">
                                      <div class="input-group-addon" style="width:0.009%"><img src="~/Content/icons/estado-icon.png" width="18px"/></div>
                                        @Html.DropDownListFor(model => model.EstadoId, (SelectList)ViewBag.EstadoId, new {@class="selectpicker"})
                                    </div>
                                    <p>
                                    @Html.ValidationMessageFor(model => model.EstadoId)
                                    </p>
                                </div>

  @*                              <div class="editor-label">
                                    @Html.Label("Imagen")
                                </div>
                                <div class="editor-field">
                                        <input type="file" name="Imagen" /> <br />
                                    <p>
                                    @Html.ValidationMessageFor(model => model.EstadoId)
                                    </p>
                                </div>*@

                            </div>
		                    <div class="col-md-1 column">
		                    </div>
                            
		                    <div class="col-md-6 column">
                                <div class="editor-label">
                                    @Html.Label("Imagen Guía")
                                </div>
                                <p>
                                <canvas id="preview" style="background-image: url(/Content/images/car-watermark.png); border:1.5px solid #808080; width:200px; height:140px; border-radius:3px">
                                </canvas></p>
                                <input type="file" id="pic" name="pic" />
		                    </div>

                        </div>

                        </div>
                    </div>            


		</div>
	</div>
        
    <div class="row clearfix">
	    <div class="col-md-11 column" style="text-align:center">
            <p>
                <button type="submit" class="btn btn-success">GRABAR</button>&nbsp;&nbsp;
                <a href="@Url.Action("Index", "Proveedor")" class="btn btn-danger" style="margin: auto; color: #ffffff;">
                    CANCELAR
                </a>
            </p>
        </div>
    </div>

}

<script src="~/Scripts/boot.js"></script>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Thc.Web/Views/Auto/Index.cshtml
@model IEnumerable<Thc.Models.Models.Auto>

@{
    ViewBag.Title = "Vehículos";
}






	<div class="row clearfix">
		<div class="col-md-2 column">
		</div>
		<div class="col-md-8 column">
            <div class="panel panel-primary">
              <div class="panel-heading">
                <h1>Lista de Vehículos</h1>
              </div>
              <div class="panel-body">
                <form method="GET" class="navbar-form navbar-left" role="search">
                    <div class="form-group">
                        <input type="text" name="buscar" class="form-control" size="25"/>
                    </div>&nbsp;&nbsp;&nbsp;
                    <button type="submit" class="btn btn-success">Buscar</button>
                </form>
                <div align="right">
                    <a href="@Url.Action("Create", "Auto")" class="btn btn-warning" style="margin: auto; color: #ffffff;">
                        Registrar Vehículo
                    </a>
                </div>
              </div>
              <div class="panel-body">
                <table class="table table-condensed table-striped">
                    <tr class="info text-primary" style="font-size:12.5px; text-align:center">
                    <th>
                    </th>
                    <th>
                    </th>
                    <th>
                        Placa
                    </th>
                    <th>
                        Unidad
                    </th>
                    <th>
                        Estado Actual
                    </th>
                    <th>
                        Acción
                    </th>
                </tr>

            @foreach (var item in Model) {
                <tr>
                    <td>
                    </td>
                    <td>
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Placa)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Unidad.DescripcionUnidad)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Estado.DescripcionEstado)
                    </td>
                    <td align="left">
                        <img src="~/Content/icons/pencil-icon.png" title="Editar" width="16px"/>&nbsp;
                        <img src="~/Content/icons/delete-icon.png" title="Eliminar"  width="18px"/>
                    </td>
                </tr>
            }

                </table>
              </div>
            </div>
		</div>
		<div class="col-md-2 column">
		</div>
	</div>